manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: jgliao248
      url-base: https://github.com/jgliao248/zmk-keyhive-sofle-rgb
  projects:
    - name: zmk
      remote: jgliao248
      revision: sofle
      import: app/west.yml
  self:
    path: config
